import React from "react";

/**
 * Optimized <picture> wrapper.
 * Serves /images/<name>.webp first, then /images/<name>.min.png, then /images/<name>.png.
 * All assets are pre-generated by `scripts/compress-images.mjs`.
 */
interface Props extends React.ImgHTMLAttributes<HTMLImageElement> {
  name: string;
  alt: string;
}

const OptimizedImage = React.forwardRef<HTMLImageElement, Props>(
  ({ name, alt, className, loading = "lazy", decoding = "async", ...rest }, ref) => {
    const base = `/images/${name}`;
    return (
      <picture>
        <source srcSet={`${base}.webp`} type="image/webp" />
        <source srcSet={`${base}.min.png`} type="image/png" />
        <img
          ref={ref}
          src={`${base}.png`}
          alt={alt}
          className={className}
          loading={loading}
          decoding={decoding}
          {...rest}
        />
      </picture>
    );
  }
);

OptimizedImage.displayName = "OptimizedImage";
export default OptimizedImage;
